1)

In [ ]:
import numpy as np


arr = np.random.randint(1, 101, size=(5, 5))
print("Array:\n", arr)


Array:
 [[52 28 13 53 68]
 [23  9 84 93 38]
 [60 76 18 27 32]
 [32 39 11 44  2]
 [21 58 98 74 24]]


a)

In [ ]:
middle_element = arr[2, 2]
print("Middle element:", middle_element)


Middle element: 18


b)

In [ ]:
row_means = np.mean(arr, axis=1)
print("Mean of each row:", row_means)


Mean of each row: [42.8 49.4 42.6 25.6 55. ]


c)

In [ ]:
overall_mean = np.mean(arr)
greater_than_mean = arr[arr > overall_mean]

print("Overall mean:", overall_mean)
print("Elements greater than overall mean:", greater_than_mean)


Overall mean: 43.08
Elements greater than overall mean: [52 53 68 84 93 60 76 44 58 98 74]


d)

In [ ]:
def numpy_spiral_order(matrix):
    result = []
    top, bottom = 0, matrix.shape[0] - 1
    left, right = 0, matrix.shape[1] - 1

    while top <= bottom and left <= right:
        # Left to right
        for i in range(left, right + 1):
            result.append(matrix[top][i])
        top += 1

        # Top to bottom
        for i in range(top, bottom + 1):
            result.append(matrix[i][right])
        right -= 1

        if top <= bottom:
            # Right to left
            for i in range(right, left - 1, -1):
                result.append(matrix[bottom][i])
            bottom -= 1

        if left <= right:
            # Bottom to top
            for i in range(bottom, top - 1, -1):
                result.append(matrix[i][left])
            left += 1

    return result


# Test the function
spiral = numpy_spiral_order(arr)
print("Spiral Order:", spiral)


Spiral Order: [np.int64(52), np.int64(28), np.int64(13), np.int64(53), np.int64(68), np.int64(38), np.int64(32), np.int64(2), np.int64(24), np.int64(74), np.int64(98), np.int64(58), np.int64(21), np.int64(32), np.int64(60), np.int64(23), np.int64(9), np.int64(84), np.int64(93), np.int64(27), np.int64(44), np.int64(11), np.int64(39), np.int64(76), np.int64(18)]


2

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("videogamesales.csv")
df.head()


,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales
0,Asteroids,2600,1980.0,Shooter,Atari,4.00,0.26,0.0,0.05
1,Missile Command,2600,1980.0,Shooter,Atari,2.56,0.17,0.0,0.03
2,Kaboom!,2600,1980.0,Misc,Activision,1.07,0.07,0.0,0.01
3,Defender,2600,1980.0,Misc,Atari,0.99,0.05,0.0,0.01
4,Boxing,2600,1980.0,Fighting,Activision,0.72,0.04,0.0,0.01


a)

In [ ]:
df['Global_Sales'] = (
    df['NA_Sales'] +
    df['EU_Sales'] +
    df['JP_Sales'] +
    df['Other_Sales']
)

df_sorted = df.sort_values(by='Global_Sales', ascending=False)
print(df_sorted[['Name', 'Global_Sales']].head())


b)

In [ ]:
genre_sales = df.groupby('Genre')['Global_Sales'].sum()

plt.figure(figsize=(10, 6))
genre_sales.plot(kind='bar')
plt.title("Total Global Sales by Genre")
plt.xlabel("Genre")
plt.ylabel("Total Sales (Millions)")
plt.xticks(rotation=45)
plt.show()


c)

In [ ]:
gta_games = df[df['Name'].str.contains('Grand Theft Auto', case=False, na=False)]

gta_df = gta_games[['Name', 'Platform', 'Year', 'EU_Sales', 'JP_Sales']]
gta_df['EU_JP_Sales'] = gta_df['EU_Sales'] + gta_df['JP_Sales']

gta_df = gta_df[['Name', 'Platform', 'Year', 'EU_JP_Sales']]
gta_df


d)

In [ ]:
gta_sales = {
    'North America': gta_games['NA_Sales'].sum(),
    'Europe': gta_games['EU_Sales'].sum(),
    'Japan': gta_games['JP_Sales'].sum(),
    'Other': gta_games['Other_Sales'].sum()
}

plt.figure(figsize=(7, 7))
plt.pie(gta_sales.values(), labels=gta_sales.keys(), autopct='%1.1f%%')
plt.title("Grand Theft Auto Sales by Region")
plt.show()
